/// Human-readable labels for intake answer keys (API + client validation).
abstract final class IntakeFieldLabels {
  static const Map<String, String> _labels = {
    'email': 'Email',
    'childName': "Child's name",
    'dateOfBirth': 'Date of birth',
    'ageAtReferral': 'Age at referral',
    'childAddress': "Child's address",
    'motherName': "Mother's name",
    'motherAddress': "Mother's address",
    'motherMobile': "Mother's mobile",
    'motherEmail': "Mother's email",
    'secondParentRelationship': 'Relationship to child',
    'fatherName': "Second parent's name",
    'fatherAddress': "Second parent's address",
    'fatherMobile': "Second parent's mobile",
    'fatherEmail': "Second parent's email",
    'gpPractice': 'GP practice',
    'gpAddress': 'GP address',
    'gpPhone': 'GP phone',
    'referredBy': 'Who referred your child',
    'heardAbout': 'How you heard about us',
    'mainConcern': 'Main concern',
    'difficulties': 'Areas of difficulty',
    'assessedByOthers': 'Assessed by other professionals',
    'assessedByOthersDetails': 'Previous assessment details',
    'receivingTherapy': 'Currently receiving therapy',
    'therapyDetails': 'Current therapy details',
    'languagesExposed': 'Languages child exposed to',
    'parentLanguages': 'Languages spoken by parents',
    'childLanguages': 'Languages spoken by child',
    'familyHistory': 'Family history',
    'familyHistoryDetails': 'Family history details',
    'pregnancyHealth': 'Health during pregnancy',
    'prematureDetails': 'Premature birth details',
    'birthWeight': 'Birth weight',
    'birthComplications': 'Birth complications',
    'afterBirthComplications': 'Complications after birth',
    'earlyIllnesses': 'Early illnesses',
    'generalHealth': 'General health',
    'diagnosis': 'Diagnosis',
    'medications': 'Medications',
    'hospitalised': 'Hospitalised',
    'hospitalisedDetails': 'Hospitalisation details',
    'hearingTested': 'Hearing tested',
    'hearingTestedDetails': 'Hearing test details',
    'earInfections': 'Ear infections',
    'earInfectionsDetails': 'Ear infection details',
    'entInvolvement': 'ENT involvement',
    'entInvolvementDetails': 'ENT details',
    'visionTested': 'Vision tested',
    'visionTestedDetails': 'Vision test details',
    'respondsToName': 'Responds to name',
    'ageFirstWords': 'Age of first words',
    'ageTwoWordPhrases': 'Age of two-word phrases',
    'attentionListening': 'Attention and listening',
    'sentenceExamples': 'Sentence examples',
    'showsUnderstanding': 'Shows understanding',
    'temperament': 'Temperament',
    'socialSkills': 'Social skills',
    'peerInteraction': 'Peer interaction',
    'favouritePlay': 'Favourite play',
    'communicationAwareness': 'Communication awareness',
    'schoolNameAddress': 'School / nursery',
    'nurseryDays': 'Nursery days',
    'senPlan': 'SEN plan or EHCP',
    'anythingElse': 'Anything else',
    'photoConsent': 'Photo consent',
    'completedBy': 'Form completed by',
  };

  static String labelFor(String fieldKey) =>
      _labels[fieldKey] ?? fieldKey.replaceAll(RegExp(r'([A-Z])'), ' \$1').trim();
}
