/**
 * Deterministic golden case aggregate for the FHIR export (DEV-27).
 *
 * This is the single source of truth for the representative, fully-populated UK
 * case used by:
 *  - the unit tests (`src/__tests__/fhir-export.test.ts`), and
 *  - the committed golden Bundle (`golden-bundle.json`), regenerated by
 *    `scripts/gen-golden-bundle.mts`, which the **official HL7 FHIR validator**
 *    validates against the pinned UK Core R4 IG in CI (the authoritative gate).
 *
 * Keep it deterministic: fixed UUIDs, fixed timestamps, a fixed `NOW`. Every
 * mappable resource is present so the golden Bundle exercises the whole mapper.
 */

import type { CaseAggregate } from "../mappers.js";

/** Fixed export instant so `toBundle` output (and golden JSON) is reproducible. */
export const GOLDEN_NOW = new Date("2026-06-15T10:00:00.000Z");

/** A fully-populated UK case — every mappable resource is present. */
export function goldenCase(): CaseAggregate {
  return {
    tenant: {
      id: "11111111-1111-1111-1111-111111111111",
      displayName: "Bright Voices SLT",
      location: "Manchester, UK",
      jurisdiction: "uk",
    },
    case: {
      id: "22222222-2222-2222-2222-222222222222",
      tenantId: "11111111-1111-1111-1111-111111111111",
      status: "carryover",
      parentEmail: "parent@example.com",
      parentPhone: "+447700900000",
      childDisplayName: "Ada Lovelace",
      childGivenName: "Ada",
      childFamilyName: "Lovelace",
      childDob: "2019-12-10",
      parentGivenName: "Mary",
      parentFamilyName: "Lovelace",
      parentRelationship: "mother",
      referralSource: "gp",
      // Past consult -> Encounter.
      consultAt: new Date("2026-05-01T09:00:00.000Z"),
      createdAt: new Date("2026-04-01T09:00:00.000Z"),
      updatedAt: new Date("2026-06-01T09:00:00.000Z"),
    },
    intake: {
      id: "33333333-3333-3333-3333-333333333333",
      answers: { mainConcern: "Speech sounds", photoConsent: "yes", version: 1 },
      consentVersion: "mvp-v1",
      locked: true,
      submittedAt: new Date("2026-04-05T09:00:00.000Z"),
    },
    triage: [
      {
        id: "44444444-4444-4444-4444-444444444444",
        outcome: "strategy_only",
        reason: "Mild; strategies sufficient.",
        recordedAt: new Date("2026-04-10T09:00:00.000Z"),
      },
    ],
    drafts: [
      {
        id: "55555555-5555-5555-5555-555555555555",
        kind: "prep_brief",
        content: { brief: "working notes" },
        reviewedAt: new Date("2026-04-09T09:00:00.000Z"),
        createdAt: new Date("2026-04-08T09:00:00.000Z"),
      },
      {
        id: "66666666-6666-6666-6666-666666666666",
        kind: "session_plan",
        content: { plan: "x" },
        reviewedAt: new Date("2026-04-11T09:00:00.000Z"),
        createdAt: new Date("2026-04-10T09:00:00.000Z"),
      },
      {
        id: "77777777-7777-7777-7777-777777777777",
        kind: "parent_summary",
        content: { html: "<p>summary</p>" },
        reviewedAt: new Date("2026-04-12T09:00:00.000Z"),
        createdAt: new Date("2026-04-11T09:00:00.000Z"),
      },
      {
        id: "88888888-8888-8888-8888-888888888888",
        kind: "clinical_report",
        content: { sections: [] },
        reviewedAt: new Date("2026-04-13T09:00:00.000Z"),
        createdAt: new Date("2026-04-12T09:00:00.000Z"),
      },
      {
        // Unreviewed -> MUST be excluded.
        id: "99999999-9999-9999-9999-999999999999",
        kind: "clinical_report",
        content: {},
        reviewedAt: null,
        createdAt: new Date("2026-04-14T09:00:00.000Z"),
      },
    ],
    carryover: [
      {
        id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        title: "Daily sound practice",
        description: "5 minutes a day",
        url: "https://example.com/r",
        category: "home_practice",
        createdAt: new Date("2026-06-01T09:00:00.000Z"),
      },
    ],
    progress: [
      {
        id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        author: "parent",
        note: "We tried it.",
        rating: "going_well",
        createdAt: new Date("2026-06-05T09:00:00.000Z"),
      },
    ],
  };
}
