import { eq } from "drizzle-orm";
import type { Db } from "../db/client.js";
import { aiDrafts, cases, intakeSubmissions } from "../db/schema.js";
import { writeAudit } from "./audit.js";

/**
 * Session plan content shape — same whether generated by the stub or, later,
 * by the air-gap LLM (ADR-003). Clinician edits write back into this shape
 * via `PUT /v1/cases/:id/session-plan`.
 */
export interface SessionPlanContent {
  label: string;
  reviewStatus: "draft" | "final";
  sections: {
    goals: string[];
    activities: string[];
    homePractice: string[];
    materials: string[];
    parentGoals: string[];
  };
  source: "mvp_stub" | "clinician_edited";
}

export async function draftSessionPlanStub(db: Db, caseId: string) {
  const [row] = await db.select().from(cases).where(eq(cases.id, caseId));
  if (!row) return { ok: false as const, error: "not_found" };

  const existing = await db
    .select()
    .from(aiDrafts)
    .where(eq(aiDrafts.caseId, caseId));
  if (existing.some((d) => d.kind === "session_plan")) {
    return { ok: true as const, alreadyExists: true };
  }

  const [intake] = await db
    .select()
    .from(intakeSubmissions)
    .where(eq(intakeSubmissions.caseId, caseId));
  const answers = (intake?.answers ?? {}) as Record<string, unknown>;

  const content = buildStubSessionPlan(answers);

  const [draft] = await db
    .insert(aiDrafts)
    .values({
      caseId,
      kind: "session_plan",
      content,
      modelId: "mvp-stub",
    })
    .returning();

  await db
    .update(cases)
    .set({ status: "plan_ready", updatedAt: new Date() })
    .where(eq(cases.id, caseId));

  await writeAudit(db, {
    tenantId: row.tenantId,
    caseId,
    actor: "system",
    action: "session_plan.drafted",
  });

  return { ok: true as const, draft };
}

/**
 * Update an existing session-plan draft (clinician edits, or mark final).
 * Returns 404 if no plan draft exists yet — the stub generator must have run
 * (triggered automatically after triage).
 */
export async function updateSessionPlan(
  db: Db,
  caseId: string,
  patch: {
    sections?: SessionPlanContent["sections"];
    reviewStatus?: SessionPlanContent["reviewStatus"];
  },
) {
  const [row] = await db.select().from(cases).where(eq(cases.id, caseId));
  if (!row) return { ok: false as const, error: "not_found" };

  const drafts = await db
    .select()
    .from(aiDrafts)
    .where(eq(aiDrafts.caseId, caseId));
  const plan = drafts.find((d) => d.kind === "session_plan");
  if (!plan) {
    return { ok: false as const, error: "session_plan_not_drafted" };
  }

  const current = (plan.content as SessionPlanContent | null) ?? null;
  const merged: SessionPlanContent = {
    label: "DRAFT — clinician must review",
    reviewStatus: patch.reviewStatus ?? current?.reviewStatus ?? "draft",
    sections: {
      goals: patch.sections?.goals ?? current?.sections.goals ?? [],
      activities: patch.sections?.activities ?? current?.sections.activities ?? [],
      homePractice:
        patch.sections?.homePractice ?? current?.sections.homePractice ?? [],
      materials: patch.sections?.materials ?? current?.sections.materials ?? [],
      parentGoals:
        patch.sections?.parentGoals ?? current?.sections.parentGoals ?? [],
    },
    source: patch.sections ? "clinician_edited" : current?.source ?? "mvp_stub",
  };

  const [updated] = await db
    .update(aiDrafts)
    .set({
      content: merged,
      reviewedAt: merged.reviewStatus === "final" ? new Date() : null,
    })
    .where(eq(aiDrafts.id, plan.id))
    .returning();

  await writeAudit(db, {
    tenantId: row.tenantId,
    caseId,
    actor: "clinician",
    action:
      merged.reviewStatus === "final"
        ? "session_plan.finalised"
        : "session_plan.edited",
  });

  return { ok: true as const, draft: updated };
}

/** Derives the stub plan from the parent's intake answers. */
export function buildStubSessionPlan(
  answers: Record<string, unknown>,
): SessionPlanContent {
  const concerns = str(answers.mainConcern);
  const difficulties = arr(answers.difficulties);
  const ageAtReferral = str(answers.ageAtReferral);
  const senPlan = str(answers.senPlan);
  const focus = pickFocus(concerns, difficulties);

  const goals: string[] = [];
  const activities: string[] = [];
  const homePractice: string[] = [];
  const materials: string[] = [];
  const parentGoals: string[] = [];

  switch (focus) {
    case "speech_sounds":
      goals.push(
        "Establish baseline of speech-sound inventory (DEAP screen).",
        "Identify 2–3 priority targets (final-consonant deletion, stopping).",
      );
      activities.push(
        "Play-based articulation probe — picture-naming for 24 single words.",
        "Auditory bombardment using target sounds in short play sequences.",
      );
      homePractice.push(
        "5 minutes daily of 'silly sound' play using the target sound list.",
        "Read one picture book using exaggerated final consonants.",
      );
      materials.push(
        "DEAP articulation cards",
        "Sound symbol prompts (printable)",
      );
      parentGoals.push(
        "Notice + acknowledge clear speech rather than correct errors.",
        "Use one focused 5-minute practice slot daily.",
      );
      break;

    case "fluency":
      goals.push(
        "Baseline % syllables stuttered across 3 contexts.",
        "Reduce avoidance behaviours in low-pressure contexts.",
      );
      activities.push(
        "Easy-onset breathing demo + paired practice.",
        "Conversation sample — recorded and shared back with parent.",
      );
      homePractice.push(
        "Slow conversation game at dinner: parent models slower pace.",
        "Daily 5-minute 'special time' with no interruptions.",
      );
      materials.push(
        "Fluency self-rating chart (parent-friendly)",
        "Stammering Information Programme parent leaflet",
      );
      parentGoals.push(
        "Reduce time-pressure and demand questions.",
        "Maintain eye contact and natural reactions during disfluencies.",
      );
      break;

    case "social_communication":
      goals.push(
        "Profile of strengths + difficulties in conversation + non-literal language.",
        "Build a personalised conversation 'cheat sheet' for school.",
      );
      activities.push(
        "Conversation probe — topic management + repair strategies.",
        "Idiom + sarcasm sort (Pokemon-themed for engagement).",
      );
      homePractice.push(
        "5-minute video-clip game: pause + predict what the character means.",
        "Lunchtime conversation rotation card.",
      );
      materials.push(
        "Conversation rules visual",
        "Social inference picture deck",
      );
      parentGoals.push(
        "Explicitly label idioms / sarcasm in everyday talk.",
        "Help child rehearse 1 conversation per day with a peer.",
      );
      break;

    case "feeding":
      goals.push(
        "Document accepted-food inventory + sensory profile of refusals.",
        "Expand accepted textures by 1 new texture in 4 weeks.",
      );
      activities.push(
        "Play-based food exploration (no expectation to eat).",
        "Parent interview — current strategies + family mealtime routine.",
      );
      homePractice.push(
        "Tolerance ladder — 1 step per week, no pressure to taste.",
        "Joint cooking activity once per week (mix + smell only).",
      );
      materials.push(
        "Food acceptance log (weekly)",
        "Sensory-friendly mealtime kit (textured spoons, weighted bowl)",
      );
      parentGoals.push(
        "Drop coercive strategies; celebrate exploration not eating.",
        "Liaise with OT around sensory co-regulation at mealtimes.",
      );
      break;

    case "language_general":
    default:
      goals.push(
        "Profile receptive + expressive language using informal assessment.",
        "Identify 2 priority goals from parent + clinician shortlist.",
      );
      activities.push(
        "Play-based observation 20 minutes.",
        "Parent interview probes from prep brief.",
      );
      homePractice.push(
        "5-minute daily 'special time' with shared book.",
        "Short daily practice suggestion (clinician refines after first session).",
      );
      materials.push(
        "Picture book selection",
        "Parent handout: language enrichment at home",
      );
      parentGoals.push(
        "Slow down + add 1 word to child utterances.",
        "Reduce closed questions; increase comments.",
      );
      break;
  }

  if (ageAtReferral && Number(ageAtReferral) >= 7) {
    goals.push("Discuss child involvement in goal-setting (age appropriate).");
  }
  if (senPlan && /ehcp/i.test(senPlan)) {
    parentGoals.push("Coordinate goals with EHCP review cycle.");
  }

  return {
    label: "DRAFT — clinician must review",
    reviewStatus: "draft",
    sections: { goals, activities, homePractice, materials, parentGoals },
    source: "mvp_stub",
  };
}

function str(v: unknown): string {
  return typeof v === "string" ? v : "";
}
function arr(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];
}

type Focus =
  | "speech_sounds"
  | "fluency"
  | "social_communication"
  | "feeding"
  | "language_general";

function pickFocus(concern: string, difficulties: string[]): Focus {
  const lc = concern.toLowerCase();
  const diffLc = difficulties.map((d) => d.toLowerCase());

  if (
    lc.includes("stutter") ||
    lc.includes("fluency") ||
    lc.includes("stammer")
  ) {
    return "fluency";
  }
  if (
    lc.includes("feed") ||
    lc.includes("fussy") ||
    lc.includes("texture") ||
    lc.includes("food")
  ) {
    return "feeding";
  }
  if (
    lc.includes("social communication") ||
    diffLc.some((d) =>
      ["eye contact", "turn taking", "reading between the lines", "topic"].some(
        (k) => d.includes(k),
      ),
    )
  ) {
    return "social_communication";
  }
  if (
    diffLc.some((d) => d.includes("speech sound") || d.includes("articulat")) ||
    lc.includes("speech sound") ||
    lc.includes("articulat")
  ) {
    return "speech_sounds";
  }
  return "language_general";
}
